const RECAP_QUESTIONS = {
  1: [
    { question: "What does print() do?", options: ["Shows words on the screen", "Deletes your code", "Turns off the computer"], answer: 0 },
    { question: "What is a computer program?", options: ["A list of steps that tells the computer what to do", "A type of snack", "A picture only"], answer: 0 },
    { question: "What wraps around the words we want to print?", options: ["Quotes", "Nothing at all", "A hat"], answer: 0 },
    { question: "What language are we learning?", options: ["Python", "Pizza", "Dinosaur"], answer: 0 },
    { question: "What button tests your code?", options: ["▶ Run", "Close the tab", "The power button"], answer: 0 },
  ],
  2: [
    { question: "How many lines does one print() make?", options: ["1 line", "2 lines", "0 lines"], answer: 0 },
    { question: "If you write print() two times, how many lines show up?", options: ["2 lines", "1 line", "10 lines"], answer: 0 },
    { question: "Which line does Python read first?", options: ["The top line", "The bottom line", "Whichever it feels like"], answer: 0 },
    { question: "Can you print two different messages?", options: ["Yes, with two print() lines", "No, only one ever", "Only with turtle"], answer: 0 },
    { question: "What do we call words inside quotes?", options: ["A string", "A number", "A loop"], answer: 0 },
  ],
  3: [
    { question: "What is a variable like?", options: ["A labeled box that holds something", "A type of pizza", "A loop"], answer: 0 },
    { question: "How do we put a name in a box called my_name?", options: ['my_name = "Alex"', "print(my_name)", "my_name + Alex"], answer: 0 },
    { question: "How do we show what's inside the box?", options: ["print(my_name)", "print(\"my_name\")", "delete my_name"], answer: 0 },
    { question: "Does print(my_name) use quotes around my_name?", options: ["No quotes needed", "Yes, always", "Only on weekends"], answer: 0 },
    { question: "What side of = do we put the value on?", options: ["The right side", "The left side", "Neither side"], answer: 0 },
  ],
  4: [
    { question: "What does True mean?", options: ["Yes", "No", "Maybe"], answer: 0 },
    { question: "What does False mean?", options: ["No", "Yes", "Maybe"], answer: 0 },
    { question: "What word helps the computer make a choice?", options: ["if", "print", "loop"], answer: 0 },
    { question: "If is_sunny is False, which message runs?", options: ["The else message", "The if message", "Both at once"], answer: 0 },
    { question: "What must come at the end of an if line?", options: ["A colon :", "A question mark", "Nothing"], answer: 0 },
  ],
  5: [
    { question: "What does a for loop do?", options: ["Repeats a line of code", "Deletes your code", "Prints only once"], answer: 0 },
    { question: "for i in range(3): repeats the line how many times?", options: ["3 times", "1 time", "30 times"], answer: 0 },
    { question: "What must the line under for: be?", options: ["Indented (scooted right)", "In all capital letters", "Deleted"], answer: 0 },
    { question: "Why use a loop instead of typing print() 3 times?", options: ["It saves you typing", "It's not allowed otherwise", "Loops are slower"], answer: 0 },
    { question: "What comes at the end of the for line?", options: ["A colon :", "A dollar sign", "Nothing"], answer: 0 },
  ],
  6: [
    { question: "What does print() do?", options: ["Shows words on the screen", "Deletes your code", "Draws a turtle"], answer: 0 },
    { question: "Where do we put the message we want to show?", options: ["Inside parentheses ()", "On the moon", "In a backpack"], answer: 0 },
    { question: "What wraps around text like \"Hello\"?", options: ["Quotes", "Brackets only", "Nothing"], answer: 0 },
    { question: "What language are we learning?", options: ["Python", "Pizza", "Dinosaur"], answer: 0 },
    { question: "After you change code, what button tests it?", options: ["▶ Run", "Close the tab", "Delete everything"], answer: 0 },
  ],
  7: [
    { question: "What do we call words in quotes like \"Hello\"?", options: ["Strings", "Sandwiches", "Numbers"], answer: 0 },
    { question: "How do you print a second line?", options: ["Use print() again", "Turn off the computer", "Whisper"], answer: 0 },
    { question: "Each print() creates a new...?", options: ["Line", "Turtle", "Variable only"], answer: 0 },
    { question: "Can you have three or more print lines?", options: ["Yes!", "No, only one", "Only on Fridays"], answer: 0 },
    { question: "Strings use which kind of quotes?", options: ["Straight quotes like \"hi\"", "Only numbers", "No quotes ever"], answer: 0 },
  ],
  8: [
    { question: "What is a variable like?", options: ["A labeled box that stores something", "A type of pizza", "A keyboard key"], answer: 0 },
    { question: "How do we save your name in a variable?", options: ['name = "Alex"', "print(name)", "name + pizza"], answer: 0 },
    { question: "What side of = gets the value?", options: ["The right side", "The left side only", "Neither side"], answer: 0 },
    { question: "Can you print a variable's value?", options: ["Yes, with print(name)", "No, never", "Only with turtle"], answer: 0 },
    { question: "Good variable names are...?", options: ["Short and clear like age or name", "Random emoji only", "Always the number 7"], answer: 0 },
  ],
  9: [
    { question: "Which symbol means multiply?", options: ["*", "+", "/"], answer: 0 },
    { question: "Which symbol means divide?", options: ["/", "*", "#"], answer: 0 },
    { question: "Can Python do math with numbers?", options: ["Yes!", "No, only turtles", "Only on Tuesdays"], answer: 0 },
    { question: "12 / 3 equals...?", options: ["4", "36", "9"], answer: 0 },
    { question: "Variables can store...?", options: ["Numbers and math answers", "Only words", "Nothing useful"], answer: 0 },
  ],
  10: [
    { question: "Can you change what is inside a variable later?", options: ["Yes, give it a new value", "No, never", "Only if you sing"], answer: 0 },
    { question: "What makes a silly mad-libs story?", options: ["Swapping fun words in variables", "Deleting all the code", "Closing your eyes"], answer: 0 },
    { question: "If animal = \"cat\" then animal = \"dragon\", which prints?", options: ["dragon", "cat", "Both at once"], answer: 0 },
    { question: "Variables on the right of = can be...?", options: ["Any fun words in quotes", "Only numbers", "Empty always"], answer: 0 },
    { question: "print() can show several variables in one line?", options: ["Yes, like print(\"Hi\", name)", "No, one only", "Only with turtle"], answer: 0 },
  ],
  11: [
    { question: "What keyword picks between two paths?", options: ["if", "print", "turtle"], answer: 0 },
    { question: "What runs when the if test is false?", options: ["The else part", "Nothing ever", "A rocket"], answer: 0 },
    { question: "True means...?", options: ["Yes, the test passed", "No, false", "A turtle color"], answer: 0 },
    { question: "What checks if two things are equal?", options: ["==", "=", "**"], answer: 0 },
    { question: "Lines under if: must be...?", options: ["Indented (scooted right)", "Deleted", "In ALL CAPS"], answer: 0 },
  ],
  12: [
    { question: "What does a loop do?", options: ["Repeats code again and again", "Makes lunch", "Erases variables"], answer: 0 },
    { question: "range(5) helps us loop how many times?", options: ["5 times", "1 time", "100 times always"], answer: 0 },
    { question: "for i in range(3): runs how many times?", options: ["3 times", "2 times", "Forever"], answer: 0 },
    { question: "Lines inside a loop must be...?", options: ["Indented under the for line", "At the very top", "Deleted"], answer: 0 },
    { question: "What comes at the end of a for line?", options: ["A colon :", "A question mark", "Three dots"], answer: 0 },
  ],
  13: [
    { question: "What holds many items in order?", options: ["A list", "A hat", "A sandwich"], answer: 0 },
    { question: "What spot is the FIRST item in a list?", options: ["[0]", "[1]", "[99]"], answer: 0 },
    { question: "Lists use which brackets?", options: ["Square brackets [ ]", "Only parentheses", "Curly braces only"], answer: 0 },
    { question: "Items in a list are separated by...?", options: ["Commas", "Periods only", "Nothing"], answer: 0 },
    { question: "shopping[2] gets the...?", options: ["Third item", "First item", "Last item always"], answer: 0 },
  ],
  14: [
    { question: "for item in my_list: visits every...?", options: ["Item in the list", "Person on Earth", "Color in the rainbow only"], answer: 0 },
    { question: "Why use a loop instead of many prints?", options: ["It saves work when lists grow", "Loops are slower always", "Python forbids print"], answer: 0 },
    { question: "A list with 4 animals prints how many lines in a loop?", options: ["4 lines", "1 line", "0 lines"], answer: 0 },
    { question: "The word after 'for' is...?", options: ["A nickname for each item", "Always the word turtle", "Forbidden"], answer: 0 },
    { question: "Can you loop through any list?", options: ["Yes!", "Only number lists", "Only on lesson 9"], answer: 0 },
  ],
  15: [
    { question: "What module draws shapes?", options: ["turtle", "pizza", "rocket"], answer: 0 },
    { question: "How do we start the turtle?", options: ["t = turtle.Turtle()", "print(turtle)", "delete turtle"], answer: 0 },
    { question: "How do we draw a square?", options: ["Forward and turn 90° four times", "One giant jump", "Only with crayons"], answer: 0 },
    { question: "t.forward(100) makes the turtle...?", options: ["Move ahead and draw", "Turn around only", "Change color"], answer: 0 },
    { question: "t.right(90) makes the turtle...?", options: ["Turn right 90 degrees", "Move backward", "Delete the drawing"], answer: 0 },
  ],
  16: [
    { question: "t.left(90) turns the turtle...?", options: ["Left 90 degrees", "Backward", "Upside down only"], answer: 0 },
    { question: "A triangle has how many sides?", options: ["3", "4", "8"], answer: 0 },
    { question: "For a triangle, we often turn...?", options: ["120 degrees each time", "360 degrees once", "0 degrees"], answer: 0 },
    { question: "t.right() and t.left() do what?", options: ["Turn the turtle", "Change the background", "Print text"], answer: 0 },
    { question: "How do we change the turtle's line color?", options: ['t.color("red")', "t.eat()", "t.sleep()"], answer: 0 },
  ],
  17: [
    { question: "t.backward(50) makes the turtle...?", options: ["Move back 50 steps", "Turn left 50 times", "Sleep"], answer: 0 },
    { question: "backward() is the opposite of...?", options: ["forward()", "left()", "color()"], answer: 0 },
    { question: "A zigzag uses forward, backward, and...?", options: ["Turns (left or right)", "Only print()", "Deleting code"], answer: 0 },
    { question: "Does backward() still draw a line?", options: ["Yes, going the other way", "No, never", "Only in red"], answer: 0 },
    { question: "You can mix forward and backward in one program?", options: ["Yes!", "No, pick one", "Only with lists"], answer: 0 },
  ],
  18: [
    { question: "t.penup() does what?", options: ["Lifts the pen so no line is drawn", "Deletes the turtle", "Changes color"], answer: 0 },
    { question: "t.pendown() does what?", options: ["Puts the pen down to draw again", "Erases everything", "Turns off Python"], answer: 0 },
    { question: "Why use penup()?", options: ["To jump without drawing a line", "To make the turtle faster only", "To print jokes"], answer: 0 },
    { question: "Typical order for a gap: forward, penup, forward, pendown, forward?", options: ["Yes — draw, jump, draw", "No — never use penup", "Only backward works"], answer: 0 },
    { question: "Pen up/down is like...?", options: ["Lifting a real pen off paper", "Eating lunch", "A math problem"], answer: 0 },
  ],
  19: [
    { question: "What picks a random number?", options: ["random.randint()", "print()", "turtle.forward()"], answer: 0 },
    { question: "How do we check if guess equals secret?", options: ["guess == secret", "guess = secret always", "guess >> secret"], answer: 0 },
    { question: "What module gives us random numbers?", options: ["import random", "import turtle", "import pizza"], answer: 0 },
    { question: "If guess is wrong, what keyword handles the other path?", options: ["else", "loop", "list"], answer: 0 },
    { question: "Games use random numbers for...?", options: ["Dice rolls and surprises", "Only printing hello", "Deleting files"], answer: 0 },
  ],
  20: [
    { question: "What did you combine in the final project?", options: ["Variables, print, loops, and turtle", "Only one line of code", "Nothing at all"], answer: 0 },
    { question: "Can one program use many skills together?", options: ["Yes — that's real coding!", "No, one skill only", "Only for experts"], answer: 0 },
    { question: "Lists store hobbies like...?", options: ['["soccer", "art", "music"]', "Only one hobby", "No brackets"], answer: 0 },
    { question: "The final project is about...?", options: ["YOU — your name, age, and interests", "Only turtles", "Only random numbers"], answer: 0 },
    { question: "Are you ready for the final quiz and certificate?", options: ["Yes! 🎓", "Maybe in 100 years", "What's Python?"], answer: 0 },
  ],
  21: [
    { question: "What keyword starts a function?", options: ["def", "for", "if"], answer: 0 },
    { question: "Where do you put info a function needs?", options: ["In the print statement", "Inside the parentheses ()", "After return"], answer: 1 },
    { question: "What does return do?", options: ["Deletes the function", "Prints Hello automatically", "Hands back a result you can use"], answer: 2 },
    { question: "How do you run a function named greet?", options: ["def greet", "greet()", "return greet"], answer: 1 },
    { question: "Why use functions?", options: ["To make Python slower", "To delete variables", "To reuse code without retyping it"], answer: 2 },
  ],
  22: [
    { question: "What symbol pairs hold a dictionary's items?", options: ["Curly braces { }", "Square brackets [ ]", "Parentheses ( )"], answer: 0 },
    { question: "How do you look up a value in a dictionary?", options: ["By its position number", "By its key name", "By guessing"], answer: 1 },
    { question: "In pet = {\"name\": \"Rex\"}, what is \"name\"?", options: ["The value", "The key", "A loop"], answer: 1 },
    { question: "What connects a key to its value?", options: ["A comma", "A plus sign", "A colon :"], answer: 2 },
    { question: "Dictionaries store data as...?", options: ["Key/value pairs", "Only numbers", "Random letters"], answer: 0 },
  ],
  23: [
    { question: "What keyword repeats code while something is True?", options: ["while", "if", "return"], answer: 0 },
    { question: "Why must you change the variable inside a while loop?", options: ["It's not necessary", "To make it colorful", "So the loop eventually stops"], answer: 2 },
    { question: "count = 1, and it prints then adds 1 while count <= 3. How many times does it print?", options: ["2 times", "3 times", "Forever"], answer: 1 },
    { question: "A while loop keeps going as long as its condition is...?", options: ["True", "False", "Purple"], answer: 0 },
    { question: "What happens if you forget to change the variable?", options: ["The code runs once", "Python deletes it", "The loop could run forever"], answer: 2 },
  ],
  24: [
    { question: "What is a loop inside another loop called?", options: ["A nested loop", "A broken loop", "A single loop"], answer: 0 },
    { question: "Outer loop runs 3 times, inner loop runs 3 times each round. How many total prints?", options: ["3", "9", "6"], answer: 1 },
    { question: "In a nested loop, which loop finishes first each round?", options: ["The outer loop", "Neither", "The inner loop"], answer: 2 },
    { question: "Nested loops are great for making...?", options: ["Grids and patterns", "Only single lines", "Errors"], answer: 0 },
    { question: "line = line + \"*\" adds a star to...?", options: ["A new list", "The end of a string", "A dictionary"], answer: 1 },
  ],
  25: [
    { question: "What keyword tries code that might break?", options: ["try", "except", "catch"], answer: 0 },
    { question: "What runs if the try block has a problem?", options: ["Nothing happens", "The program always crashes", "The except block"], answer: 2 },
    { question: "Dividing a number by zero causes what kind of error?", options: ["ValueError", "ZeroDivisionError", "NameError"], answer: 1 },
    { question: "Why use try/except?", options: ["So your program doesn't crash on errors", "To make code longer", "To delete variables"], answer: 0 },
    { question: "try/except is like a...?", options: ["Race track", "Shopping list", "Safety net for your code"], answer: 2 },
  ],
  26: [
    { question: "What does [n*n for n in nums] build?", options: ["A new list of squared numbers", "A dictionary", "Nothing, it's just a comment"], answer: 0 },
    { question: "Where do you put a condition in a comprehension?", options: ["After an if at the end", "Before the brackets", "You can't filter in a comprehension"], answer: 0 },
    { question: "[n for n in range(3)] creates which list?", options: ["[0, 1, 2]", "[1, 2, 3]", "[3]"], answer: 0 },
    { question: "A list comprehension is mainly a shorter way to write a...?", options: ["for loop that builds a list", "class", "try/except block"], answer: 0 },
    { question: "Comprehensions are written inside which brackets?", options: ["Square brackets [ ]", "Curly braces { } only", "Parentheses only"], answer: 0 },
  ],
  27: [
    { question: "nums[1:4] includes which indexes?", options: ["1, 2, 3", "1, 2, 3, 4", "0, 1, 2, 3"], answer: 0 },
    { question: "What does nums[-1] mean?", options: ["The last item", "The first item", "An error"], answer: 0 },
    { question: "What does nums[::-1] do?", options: ["Reverses the list", "Sorts the list", "Deletes the list"], answer: 0 },
    { question: "nums[:2] means...?", options: ["From the start up to index 2", "From index 2 to the end", "Only index 2"], answer: 0 },
    { question: "Is the stop number in a slice included?", options: ["No, it stops right before it", "Yes, always", "Only for negative numbers"], answer: 0 },
  ],
  28: [
    { question: "Once made, can you change what's inside a tuple?", options: ["No, tuples are locked", "Yes, anytime", "Only the first item"], answer: 0 },
    { question: "What does a set automatically remove?", options: ["Duplicate values", "The first item", "All the numbers"], answer: 0 },
    { question: "Which brackets make a tuple?", options: ["( )", "[ ]", "{ }"], answer: 0 },
    { question: "set([1, 1, 2, 2, 3]) becomes...?", options: ["{1, 2, 3}", "{1, 1, 2, 2, 3}", "An error"], answer: 0 },
    { question: "A tuple is a good fit for...?", options: ["A pair that shouldn't change, like (x, y)", "A shopping list that grows", "A dictionary key that changes"], answer: 0 },
  ],
  29: [
    { question: "What does scores.items() give you in a loop?", options: ["Both the key and value together", "Only the keys", "Only the values"], answer: 0 },
    { question: "What does .get(\"Jordan\", \"not found\") do if Jordan isn't a key?", options: ["Returns \"not found\" instead of crashing", "Crashes the program", "Adds Jordan automatically"], answer: 0 },
    { question: "for name, score in scores.items(): — name and score are...?", options: ["The key and the value", "Two random numbers", "Always the same thing"], answer: 0 },
    { question: "Why use .get() instead of scores[\"key\"]?", options: ["It won't crash if the key is missing", "It's the only way to read a dictionary", "It deletes the key"], answer: 0 },
    { question: "Dictionaries store data as...?", options: ["Key and value pairs", "Just a list of numbers", "Only text"], answer: 0 },
  ],
  30: [
    { question: "def greet(name, greeting=\"Hello\"): — what is \"Hello\"?", options: ["A default value used if greeting isn't given", "A required value every time", "An error"], answer: 0 },
    { question: "greet(\"Ana\") is called with one argument. What happens to greeting?", options: ["It uses the default, \"Hello\"", "The program crashes", "greeting becomes empty"], answer: 0 },
    { question: "greet(\"Sam\", \"Hey\") — what does greeting become?", options: ["\"Hey\"", "\"Hello\"", "Nothing"], answer: 0 },
    { question: "A default value is used when...?", options: ["You don't pass that argument yourself", "You always pass every argument", "Never — defaults are ignored"], answer: 0 },
    { question: "Why are default values useful?", options: ["They make functions flexible without extra typing", "They make code run slower", "They delete parameters"], answer: 0 },
  ],
  31: [
    { question: "What is __init__ for?", options: ["It sets up a new object when it's created", "It deletes an object", "It prints text"], answer: 0 },
    { question: "What does self refer to?", options: ["This specific object", "Every object of every class", "The class name"], answer: 0 },
    { question: "A class is best described as a...?", options: ["Blueprint for making objects", "A single number", "A type of loop"], answer: 0 },
    { question: "Robot(\"Rusty\", 80) creates...?", options: ["A new Robot object with its own name and battery", "A function", "A dictionary"], answer: 0 },
    { question: "self.name = name inside __init__ does what?", options: ["Saves name onto this object so it can be used later", "Prints the name", "Deletes the name"], answer: 0 },
  ],
  32: [
    { question: "What does NumPy let programmers do?", options: ["Do math on a whole list of numbers at once", "Draw turtle graphics", "Send emails"], answer: 0 },
    { question: "The trick of applying math to a whole list at once is called...?", options: ["Vectorization", "Indentation", "Slicing"], answer: 0 },
    { question: "Why can't this browser tutorial run NumPy?", options: ["It needs a full Python install, not just Skulpt", "NumPy doesn't exist", "NumPy only works with turtle"], answer: 0 },
    { question: "Which library is used for making charts and graphs?", options: ["Matplotlib", "Skulpt", "Turtle"], answer: 0 },
    { question: "Where can you try real NumPy for free in a browser?", options: ["Google Colab", "This tutorial", "You can't try it anywhere"], answer: 0 },
  ],
};

function getRecapForLesson(id) {
  return RECAP_QUESTIONS[id] || [];
}
